### ISSUE TITLE
Standardize city names

### ISSUE THREAD

**Issue by martj42** [martj42/international_results#10]
Currently, some cities exist under different spellings in the dataset e.g. Kiev and Kyïv or Cádiz and Cadiz. One needs to be picked. Possibly whichever one English Wikipedia uses. As a reminder to myself - the preferred spelling for the capital of Ukraine seems to be Kyiv.

**Comment by martj42** [comment]
A bunch were fixed in https://github.com/martj42/international_results/commit/1b49e1722ac73fc8887814519d60f249350b559f.

**Comment by kossoff** [comment]
Hi!

English Wikipedia is good example, but some languages have some problems. Best way is to have vocabulary with frequently used names of cities and base used in your dataset.

**Comment by martj42** [comment]
All cities should now have unique names.
