### ISSUE TITLE
Add managers

### ISSUE THREAD

**Issue by martj42** [martj42/international_results#12]
Shouldn't be too hard. Just go through it team-by-team.

**Comment by martj42** [comment]
Ok, actually might be quite hard. Still, something to get to eventually.

**Comment by AlunHewinson** [comment]
There are probably instances where a country has more than one manager at the same time.
One variant of this that springs to mind is Ryan Giggs who is currently Wales manager, and Rob Page who is actually in charge of matches due to an ongoing legal case against Giggs. There may other variants of multiple simultaneous managers.

As with the players, my personal recommendation is a manager table and link table. Even more so than players, you'd want to be able to track where the same manager has manager multiple countries. For fun, check out how many national teams Rudi Gutendorf manager in his 35 years of international management!

**Comment by martj42** [comment]
There are definitely cases where a country has more than one manager at the same time - Denmark or Sweden had that set-up not too long ago. With the Giggs/Page case, I don't see how Giggs could be getting the credit for the Euro matches. Unless he's actually running the team and Page just follows his orders during the match?

I think I'd like to have the managers in a separate file with `match_id` `team` and `manager_id` columns. That way it's tidier to include dual managers as well (each gets a row for each match instead of having both in the same cell).

Also, probably will use the same ids for managers and goalscorers. I see no reason not to. So we can see that the same Ryan Giggs scored goals and managed Wales.

**Comment by m-rossini** [comment]
Just wondering how hard, or not, is to get this information. Any ideas? Also how to you see others contributing here?

**Comment by martj42** [comment]
It's easy enough to get the basic data from, say, transfermarkt.com. But their records aren't perfect either so some kind of a manual check will have to be done too.

Most of all, error-checking is what I'd hope for from others.

**Comment by m-rossini** [comment]
On the site you mentioned I could not find any useful information (probably my bad)
https://en.wikipedia.org/wiki/List_of_European_national_football_team_managers
This is promising though. Maybe a trial?

**Comment by martj42** [comment]
Transfermarkt has the data here: https://www.transfermarkt.com/argentinien/mitarbeiterhistorie/verein/3437

Though these have missing and weird overlaps. 

Each team on Wikipedia has some kind of a table like so: https://en.wikipedia.org/wiki/Argentina_national_football_team#Manager_history which is nice but usually don't have exact starting dates. But some teams do: https://en.wikipedia.org/wiki/Norway_national_football_team#Managers

Also, rsssf is worth looking at: http://www.rsssf.com/tablesa/arg-intres.html#coachs-total

**Comment by martj42** [comment]
The more I think about it, the less I like the idea:
1. The data is already out there in a pretty decent format.
2. It would (possibly) give out undue credit and attention.

**Comment by MohamedAliRashad** [comment]
This dataset is amazing and it will be even better with managers added
