### ISSUE TITLE
Wrong Date in Matches

### ISSUE THREAD

**Issue by m-rossini** [martj42/international_results#20]
2022-**19**-22,Rwanda,Sudan,0,0,Friendly,Kigali,Rwanda,FALSE  ---->>>> Is this match a real one? Both seems to be at same date
2022-**19**-22,Rwanda,Sudan,1,0,Friendly,Kigali,Rwanda,FALSE

which I believe should be:
2022-11-19

**Comment by martj42** [comment]
Thanks. It's supposed to be two separate games - on the 17th and on the 19th.
